"""add executive briefs model

Revision ID: e6f614c959c8
Revises: 68a43c670f24
Create Date: 2026-06-24 14:55:31.139789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e6f614c959c8"
down_revision: Union[str, Sequence[str], None] = "68a43c670f24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executive_briefs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("brief_date", sa.Date(), nullable=False),
        sa.Column(
            "structured_brief", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("rendered_brief", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "brief_date", name="uq_user_brief_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("executive_briefs")
    # ### end Alembic commands ###
