"""add_knowledge_provenance_and_reviews

Revision ID: f6a4430c0840
Revises: 4ff77e116739
Create Date: 2026-06-25 16:32:17.695649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a4430c0840'
down_revision: Union[str, Sequence[str], None] = '4ff77e116739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deadlines', sa.Column('source_conversation_id', sa.UUID(), nullable=True))
    op.add_column('deadlines', sa.Column('extractor_version', sa.String(), nullable=True))
    op.add_column('deadlines', sa.Column('review_state', sa.String(), nullable=True))
    op.create_foreign_key(None, 'deadlines', 'conversations', ['source_conversation_id'], ['id'])
    op.add_column('decisions', sa.Column('source_conversation_id', sa.UUID(), nullable=True))
    op.add_column('decisions', sa.Column('extractor_version', sa.String(), nullable=True))
    op.add_column('decisions', sa.Column('review_state', sa.String(), nullable=True))
    op.create_foreign_key(None, 'decisions', 'conversations', ['source_conversation_id'], ['id'])
    op.add_column('facts', sa.Column('source_conversation_id', sa.UUID(), nullable=True))
    op.add_column('facts', sa.Column('extractor_version', sa.String(), nullable=True))
    op.add_column('facts', sa.Column('review_state', sa.String(), nullable=True))
    op.create_foreign_key(None, 'facts', 'conversations', ['source_conversation_id'], ['id'])
    op.add_column('tasks', sa.Column('source_conversation_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('extractor_version', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('review_state', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('confidence', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'conversations', ['source_conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'confidence')
    op.drop_column('tasks', 'review_state')
    op.drop_column('tasks', 'extractor_version')
    op.drop_column('tasks', 'source_conversation_id')
    op.drop_constraint(None, 'facts', type_='foreignkey')
    op.drop_column('facts', 'review_state')
    op.drop_column('facts', 'extractor_version')
    op.drop_column('facts', 'source_conversation_id')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'review_state')
    op.drop_column('decisions', 'extractor_version')
    op.drop_column('decisions', 'source_conversation_id')
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_column('deadlines', 'review_state')
    op.drop_column('deadlines', 'extractor_version')
    op.drop_column('deadlines', 'source_conversation_id')
    op.drop_table('knowledge_reviews')
    # ### end Alembic commands ###
